### ISSUE TITLE
Logo and search bar in header

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-m3diators#1]
# Story

As a user, in order to find attractions I'm interested in, I need to type some value in a text box in the navigation bar at the top of the page, press enter, and see results

# Acceptance Criteria

**Given** a user visits the application
**When** the application renders
**Then** the application logo should appear on the left in a navigation bar

**Given** a user visits the application
**When** the application renders
**Then** a text field should appear in the middle of the navigation bar

**Given** the user types some characters into the search field
**When** user user presses enter
**Then** the areas that contain an attraction, whose name contains the search string, should be outlined with a border

# Technical Information

1. Use regular expressions to match the user's search string with the name of each attraction to find a match. The search string simply must be contained in the attraction name, not just start with.

**Comment by ghost** [comment]
Wireframe:

![image](https://user-images.githubusercontent.com/23087466/32136549-3060c822-bbd5-11e7-9a49-f17db900a459.png)

**Comment by ghost** [comment]
Use the green [Bootswatch Navbar](https://bootswatch.com/sandstone/#navbar).  This can go in index.html.  Below is the code snippet from Bootswatch.  Edit to look like above wireframe.

![image](https://user-images.githubusercontent.com/23087466/32136680-90d02688-bbd7-11e7-86b3-c5174ae46b3f.png)

```<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
      </ul>
    </div>
  </div>
</nav>```

**Comment by ghost** [comment]
**Keypress Event Function**

In index.html
Create Company logo in navbar-brand
Give the text field the id of "searchBar"

In events.js
const keySearch = (event) => {};
console.log("keypress event", event);
1) This function grabs the val() of the searchbar
2) It will return those results and filter through them
3) Write to domString
4) Remove class .hidden

In main.js
const events = require('./events');

make a call to this function:
events.keySearch();

The actual printing of the card with the border will be handled in another ticket.

**Comment by annamd115** [comment]
We will be using the [Bootswatch Sandstone](https://bootswatch.com/sandstone) theme.
