### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-m3diators#12]
# Story

As a developer, in order to DO ALL THE THINGS, I need the project to be setup

# Acceptance Criteria

**When** the developer clones the repo
**Then** they should have all the files they need

To clone (in Terminal):

```mkdir Workspace/group_projects/richBrowser```

```cd Workspace/group_projects/richBrowser```

```git clone git@github.com:nss-evening-cohort-06/theme-park-m3diators.git```

**Comment by ghost** [comment]
Folders:

1. db
2. javascripts
3. lib
4. sass

**Comment by ghost** [comment]
Files:
javascripts/main.js
javascripts/events.js
lib/Grunfile.js
index.html
.gitignore
package.json
sass/_variables.scss
sass/_bootswatch.scss
sass/main.scss

**Comment by ghost** [comment]
main.js - include console.log("works?")

**Comment by ghost** [comment]
Gruntfile.js

```
module.exports = function(grunt) {

    grunt.loadNpmTasks('grunt-contrib-jshint');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-contrib-copy');
    grunt.loadNpmTasks('grunt-sass');
    grunt.loadNpmTasks('grunt-browserify');
    grunt.loadNpmTasks('grunt-contrib-clean');


    grunt.initConfig({
        browserify: {
            js: {
                src: ['../javascripts/main.js'],
                dest: '../dist/app.js'
            }
        },
        jshint: {
            options: {
                predef: ["document", "console", "$", "firebase"],
                esnext: true,
                globalstrict: true,
                globals: {},
                browserify: true
            },
            files: ['../javascripts/**/*.js']
        },
        sass: {
            dist: {
                files: {
                    '../styles/main.css': '../sass/main.scss'
                }
            }
        },
        watch: {
            options: {
                livereload: true,
            },
            sass: {
                files: ['../sass/**/*.scss'],
                tasks: ['sass']
            },
            javascripts: {
                files: ['../javascripts/**/*.js'],
                tasks: ['jshint', 'browserify']
            }
        },
        clean: {
            options: { force: true },
            public: ['../public']
        },
        copy: {
            dev: {
                files: [{
                    expand: true,
                    cwd: "../",
                    src: [
                        "index.html",
                        "db/apiKeys.json",
                        "dist/app.js",
                        "images/*",
                        "vendor/*",
                        "styles/**/*.css",
                        "lib/node_modules/bootstrap/dist/css/bootstrap.min.css",
                        "lib/node_modules/jquery/dist/jquery.min.js",
                        "lib/node_modules/bootstrap/dist/js/bootstrap.min.js",
                        "lib/node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf",
                        "lib/node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.woff",
                        "lib/node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2"
                    ],
                    dest: "../public/"
                }]
            }
        }
    });

    grunt.registerTask('default', ['jshint', 'browserify', 'sass', 'watch']);
    grunt.registerTask('deploy', ['browserify', 'sass', 'copy']);
    grunt.registerTask('cleanit', ['clean']);
};
```

**Comment by ghost** [comment]
index.html - 
1. include boilerplate html
2. links

```<link rel="stylesheet" type="text/css" href="https://bootswatch.com/sandstone/bootstrap.min.css">```
    ```<link rel="stylesheet" type="text/css" href="./styles/main.css">``` 

3. scripts
```<script type="text/javascript" src="./lib/node_modules/jquery/dist/jquery.js"></script>```
```<script type="text/javascript" src="./lib/node_modules/bootstrap/dist/js/bootstrap.js"></script>```
```<script type="text/javascript" src="./dist/app.js"></script>```

**Comment by ghost** [comment]
Put this in .gitignore

``` .DS_store```

``` lib/node_modules```

```dist/app.js```

```styles/main.css```

**Comment by ghost** [comment]
cd to lib folder in terminal and install:

```npm init```

Grunt:
```npm install grunt grunt-contrib-jshint matchdep grunt-contrib-watch grunt-sass grunt-browserify jshint-stylish --save-dev```

jQuery:
```npm install jquery bootstrap --save```

Sass:
```npm install grunt grunt-contrib-jshint matchdep grunt-contrib-watch grunt-sass grunt-browserify jshint-stylish --save-dev```

**Comment by ghost** [comment]
Put this in main.scss

```@import variables```

```@import bootswatch```

**Comment by ghost** [comment]
PR Protocol

- Each user add initials in branch name
- User makes a PR
- Write a comment to Slack @ channel
- At least 2 members must give thumbs up
- Last person to give a thumbs up will let the PR owner know the PR is good to merge via Slack
- Owner will merge and let @ channel know to pull to Master branch

Each team member will take the next open ticket, and will pair program as needed - with each person having a turn at the keyboard.

**Comment by ghost** [comment]
We will be using the [Bootswatch Superhero](https://bootswatch.com/superhero/) theme.

- Copy all code from the Sandstone [Sass Variables](https://bootswatch.com/superhero/_variables.scss) and paste into **sass/_variables.scss** 

- Copy all code from Sandstone [Sass Bootswatch](https://bootswatch.com/superhero/_bootswatch.scss) and paste into **sass/_bootswatch.scss**

**Comment by ghost** [comment]
# NSS RESOURCES ON ALL OF THESE TOPICS:
- [npm](https://github.com/nashville-software-school/front-end-milestones/blob/master/3-modern-javascript-developer/resources/MJ_NPM_INTRO.md)
- [Grunt Setup](https://github.com/nashville-software-school/front-end-milestones/blob/master/3-modern-javascript-developer/resources/MJ_GRUNT_SETUP.md)
- [Browserify](https://github.com/nashville-software-school/front-end-milestones/blob/master/3-modern-javascript-developer/resources/MJ_BROWSERIFY_CONCEPTS.md)
