### ISSUE TITLE
Project Deployed to Firebase

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-m3diators#13]
# Story

As a project manager, when I see the final product, I would like it to be served from firebase.com

# Acceptance Criteria

**When** the team demos
**Then** they should be hitting the firebase.com deployed url NOT localhost

**Comment by Matthensley777** [comment]
After firebase is set up create a URL we can demo from https://theme-park-7f89a.firebaseio.com/

**Comment by ghost** [comment]
In Terminal, the following commands must be done in the root of the project directory

**Install Firebase CLI**

The Firebase CLI (Command Line Interface) requires Node.js and npm, which can both be installed by following the instructions on https://nodejs.org/. Installing Node.js also installs npm.
`npm install -g firebase-tools`

**Initialize your app**

`firebase init`

Running the firebase init command creates a firebase.json settings file in the root of your project directory.

**The firebase.json File**

The firebase init command creates a firebase.json configuration file in the root of your project's directory. Your default firebase.json Hosting configuration will look like this:

`{
  "hosting": {
    "public": "app",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ]
  }
}`

**Add a file**

When you initialize your app, you will be prompted for a directory to use as the public root (default is "public"). If you don't already have a valid index.html file in your public root directory, one is created for you.

**Deploy your website**

`firebase deploy`

Your app will be deployed to the domain <YOUR-FIREBASE-APP>.firebaseapp.com
