### ISSUE TITLE
Areas should be displayed in rectangular grid

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-m3diators#2]
# Story

As a user, in order to see where areas are located, I need to see the park laid out in a grid

# Acceptance Criteria

**Given** the area data has been loaded
**When** the application renders
**Then** the areas should be represented to the user as a 3-3-2 grid, with the middle cell of the last row unoccupied, and each area colored with its corresponding hex value (i.e. the `colorGrid` value)

<table>
  <tr>
    <td>1</td>
    <td>2</td>
    <td>3</td>
  </tr>
  <tr>
    <td>4</td>
    <td>5</td>
    <td>6</td>
  </tr>
  <tr>
    <td>7</td>
    <td></td>
    <td>8</td>
  </tr>
</table>

**Comment by ghost** [comment]
Wireframe

![image](https://user-images.githubusercontent.com/23087466/32136609-469700c4-bbd6-11e7-8a94-8565871fe4ef.png)

**Comment by ghost** [comment]
In order to get this grid shape:

Example:

First two rows:
```<div class="row">
  <div class="col-xs-6 col-sm-4">.col-xs-6 .col-sm-4</div>
  <div class="col-xs-6 col-sm-4">.col-xs-6 .col-sm-4</div>
  <!-- Optional: clear the XS cols if their content doesn't match in height -->
  <div class="clearfix visible-xs-block"></div>
  <div class="col-xs-6 col-sm-4">.col-xs-6 .col-sm-4</div>
</div>
```

Last row:
```<div class="row">
  <div class="col-md-4">.col-md-4</div>
  <div class="col-md-4 col-md-offset-4">.col-md-4 .col-md-offset-4</div>
</div>
```

**Comment by ghost** [comment]
Create dom.js file in javascripts. It will have two functions:

**domString** - this function will take an array of park areas, loop over it and creates the domstring of cards. It should also insert a div with a class of row for 3 cards, with the last row holding 2 cards.
**printToDom** = this will append the string from domString to the dom.

**Comment by ghost** [comment]
Create a div with id parkArea in index.html

(within a well container for styling)

```
<div class="well well-lg">
<div class = "container row" id="parkArea">
  </div> 
</div>
```

**Comment by ghost** [comment]
Use [Custom Content Thumbnail](https://getbootstrap.com/docs/3.3/components/#thumbnails-custom-content).

Example:
```
<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="..." alt="...">
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>...</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
</div>
```

**Comment by ghost** [comment]
Put this in main.js

```
const dom = require('./dom');
```
