### ISSUE TITLE
User should be able to see all attractions in an area

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-m3diators#3]
# Story

As a user, in order to explore attractions near me, I need to highlight an area of the park and see all attractions in it

# Acceptance Criteria

**Given** user wants to see the attraction list of an area
**When** the user clicks on an area
**Then** all attraction names assigned to that area should be listed in the left 30% of the screen
**And** the attraction type should be in parenthesis next to the name
**And** the name should be a hyperlink

**Comment by ghost** [comment]
Create file javascripts/data.js

**Comment by ghost** [comment]
In data.js:

```const dom = require('./dom');```

Set empty arrays and object:
```attractionsArray= [];```
```areasArray = [];```
```typesArray = [];```
```parkInfo = {};```


Create promise to JSON - 
```const themParkJSON = () => {};```

Create a Getter function -
```const attractionsGetter = () => {};```

Initialize Getter function -
```const initializer = () => {};```

Get Attractions function that will return attractionsArray-
```const getAttractions = () => {};```

```module.exports = {initializer, getAttractions};```

**Comment by ghost** [comment]
In main.js

```const data = require('./data');```
```const events=require(./events);```

**Comment by ghost** [comment]
Wireframe:

![image](https://user-images.githubusercontent.com/23087466/32201647-30b32bee-bda6-11e7-958f-fdb7431f8ef3.png)

**Comment by jessrod11** [comment]
in  events.js
const data = require(./data);

parkArea function will include an on click function that returns the areasArray and typesArray  
```const parkArea =()=> {};```



```module.exports = {parkArea};```
