### ISSUE TITLE
User must see copyright information

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-m3diators#5]
# Story

As a user, in order to know when the content was last updated, I need to see the date of the copyright

# Acceptance Criteria

**Given** user visits the application
**When** the page is rendered
**Then** there should be a copyright notice in a footer element with the current year and today's date.

**Comment by ghost** [comment]
Wireframe

![image](https://user-images.githubusercontent.com/23087466/32200716-06110c1c-bda1-11e7-943b-f35b0cd7f417.png)

**Comment by Matthensley777** [comment]
display on bottom of domString;

`new Date ( list[0].dt);`

**Comment by ghost** [comment]
Create a div element in index.html with id #copyright
